all:
	python3 ../bin/svck.py -t ../tests/test_cl_gvar.sv
	python3 ../bin/svck.py -t ../tests/test_comments.sv
	python3 ../bin/svck.py -t ../tests/test_20/test_20_p.sv
	python3 ../bin/svck.py -t ../tests/test_20/test_20_f.sv
	python3 ../bin/svck.py -t ../tests/test_9/test_9_p.sv

